version: '2'
services:
  webserver:
    build: ./docker/php
    links:
      - database
    ports:
     - "8081:80"
    volumes:
      - ./webroot/:/var/www/html/
      - ./config/php/:/usr/local/etc/php/
  database:
    image: mysql:5.5
    volumes:
      - ./mysql-data/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: keinsicherespasswort
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: keinsicherespasswort
      MYSQL_DATABASE: nextcloud